### ISSUE TITLE
xcode直接崩溃

### ISSUE THREAD

**Issue by liiklin** [weflex/react-native-pingpp#1]
请问下，我直接rnpm link react-native-pingpp之后。xcode直接报错。我是刚接触ios开发。望赐教。

**Comment by yorkie** [comment]
你有试过手动link么？或者你可以把你的XCode的截图发来看看～

**Comment by liiklin** [comment]
![bfe9bd13-3e04-4ec1-957d-38fb56f9c3f2](https://cloud.githubusercontent.com/assets/7721623/12670736/b63c2422-c6a5-11e5-9240-a237b8bde8da.png)

<img width="487" alt="35764d15-fe55-43a9-80b8-1a6bb1f1b71b" src="https://cloud.githubusercontent.com/assets/7721623/12671000/a801016e-c6a7-11e5-92d6-2539313320c2.png">

找不到pingpp.h。
另外请问你有没有QQ？

**Comment by yorkie** [comment]
你应该是没有添加includePath，应该可以在Build Phases里面设置～（QQ: 550532246）

**Comment by liiklin** [comment]
<img width="825" alt="1315fa88-5db0-4c6b-b9bb-ad70a78ea816" src="https://cloud.githubusercontent.com/assets/7721623/12672406/fa2d330a-c6b0-11e5-9fe2-734ef9a918d1.png">

如果添加libRCTPingPP.a会报以上错误。
如果不添加libRCTPingPP.a会报下面的错误。
<img width="819" alt="16524e29-74cb-4ea6-bccb-ec987b2b67ee" src="https://cloud.githubusercontent.com/assets/7721623/12672567/3ce94ade-c6b2-11e5-90de-228e519e916e.png">

**Comment by Binaryify** [comment]
+1

**Comment by tyao1** [comment]
@liiklin 请问这个报undefined symbols for architecture的问题最后有解决吗 我也遇到了类似问题

**Comment by liiklin** [comment]
@xiaobuu 已经弃坑，你可以查看reactnativecn的pingxx插件。不过还是要配置。

**Comment by Binaryify** [comment]
@liiklin 方便给个地址吗

**Comment by liiklin** [comment]
@Binaryify [https://github.com/lvbingru/react-native-pingxx](pingxx)
