### ISSUE TITLE
设置完 Library Links 后呢，可以在 ObjC 里面的 AppDelegate.m 中添加如下代码：

### ISSUE THREAD

**Issue by Binaryify** [weflex/react-native-pingpp#2]
这句话里的objC是什么意思,另外在AppDelegate.m 添加代码的时候不需要import pingpp.h吗,编译的时候提示找不到pingpp

**Comment by yorkie** [comment]
ObjC 就是 Objective-C 的代码，你直接忽略就好，另外也需要包含头文件的，文档中没写只是为了强调 `openURL` 这个方法。
